general:
  buildTool: "docker"

stages:
  Build:
    dockerBuild: true
    dockerImageName: "harish496/fastapi-btp-app"
    dockerRegistryUrl: "https://index.docker.io/v1/"
    dockerRegistryCredentialsId: "dockerhub"

  Deploy:
    cfDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com/"  # change region if needed
    cfOrg: "ec4edb2ctrial"
    cfSpace: "dev"
    cfAppName: "fastapi-btp-app"
    cfCredentialsId: "sapcreds"
